name: Deploy to GitHub Pages

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yml

  deploy-lastfm:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Download build artifact
      uses: actions/download-artifact@v8
      with:
        name: build-lastfm-stats
        path: dist/lastfm-stats/browser

    - name: Copy 404 page
      run: cp dist/lastfm-stats/browser/index.html dist/lastfm-stats/browser/404.html

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.8.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: dist/lastfm-stats/browser
        target-folder: docs

  deploy-spotify:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        persist-credentials: false

    - name: Download build artifact
      uses: actions/download-artifact@v8
      with:
        name: build-spotify-stats
        path: dist/spotify-stats/browser

    - name: Copy 404 page
      run: cp dist/spotify-stats/browser/index.html dist/spotify-stats/browser/404.html

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.8.0
      with:
        repository-name: felhag/spotify-stats-web
        token: ${{ secrets.SPOTIFY_DEPLOY_PAT }}
        branch: gh-pages
        folder: dist/spotify-stats/browser
        target-folder: docs
