name: CI

on:
  push:
    branches:
      - '**'
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [lastfm-stats, spotify-stats]
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - uses: pnpm/action-setup@v6
      with:
        version: 11
    - uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm exec ng build --configuration production --project ${{ matrix.project }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v7
      with:
        name: build-${{ matrix.project }}
        path: dist/${{ matrix.project }}/browser
